### ISSUE TITLE
Shear and Breaking loads of simple mechanisms

### ISSUE THREAD

**Issue by Stuart1745** [Thaddeus-Maximus/swissarmyengineer#24]
have the option to select a COTS Gearbox. 
include the shear and breaking points for the gearboxes and output shafts.

**Comment by Thaddeus-Maximus** [comment]
I think I saw one of these once.
I may go overboard on this. Sounds fun and not too terribly hard if you assume simple things like shear.
I think I saw this somewhere once- AMB's sheet maybe? If you have any references let me know.

**Comment by Thaddeus-Maximus** [comment]
See branch [strengthcalc](https://github.com/Thaddeus-Maximus/swissarmyengineer/tree/strengthcalc)

**Comment by Thaddeus-Maximus** [comment]
![image](https://user-images.githubusercontent.com/11543788/83362643-de4d0980-a360-11ea-89e3-117a8ccae899.png)
This is the general idea that I'm building, feedback appreciated. The core is there- planetaries, gears, chains (very basic based only on tensile breaking strength), belts (without consideration for RPM), shafts (only considering torsion).

Probably would implement COTS gearboxes with a dropdown selection that auto-populates the fields with all the relevant details. I like generalized tools so I'm going to leave it generalized.

**Comment by Thaddeus-Maximus** [comment]
@Stuart1745 You should checkout the strengthcalc branch. There's uh... a lot going on in the page. It's extremely visually noisy, but I'm not sure how to best fix it. However, it works- just need to finish the writeup and test things like page exporting

**Comment by Thaddeus-Maximus** [comment]
It works, so... closed
